/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AssinarRouteImport } from './routes/assinar'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppBibliotecaRouteImport } from './routes/app.biblioteca'
import { Route as AppCalculadorasRouteImport } from './routes/app.calculadoras'
import { Route as AppCalendarioRouteImport } from './routes/app.calendario'
import { Route as AppTendenciasRouteImport } from './routes/app.tendencias'
import { Route as AppOportunidadesIndexRouteImport } from './routes/app.oportunidades.index'
import { Route as AppOportunidadesSlugRouteImport } from './routes/app.oportunidades.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AssinarRoute = AssinarRouteImport.update({
  id: '/assinar',
  path: '/assinar',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppBibliotecaRoute = AppBibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => AppRoute,
} as any)
const AppCalculadorasRoute = AppCalculadorasRouteImport.update({
  id: '/calculadoras',
  path: '/calculadoras',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarioRoute = AppCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AppRoute,
} as any)
const AppTendenciasRoute = AppTendenciasRouteImport.update({
  id: '/tendencias',
  path: '/tendencias',
  getParentRoute: () => AppRoute,
} as any)
const AppOportunidadesIndexRoute = AppOportunidadesIndexRouteImport.update({
  id: '/oportunidades/',
  path: '/oportunidades/',
  getParentRoute: () => AppRoute,
} as any)
const AppOportunidadesSlugRoute = AppOportunidadesSlugRouteImport.update({
  id: '/oportunidades/$slug',
  path: '/oportunidades/$slug',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/assinar': typeof AssinarRoute
  '/app/biblioteca': typeof AppBibliotecaRoute
  '/app/calculadoras': typeof AppCalculadorasRoute
  '/app/calendario': typeof AppCalendarioRoute
  '/app/tendencias': typeof AppTendenciasRoute
  '/app/': typeof AppIndexRoute
  '/app/oportunidades/$slug': typeof AppOportunidadesSlugRoute
  '/app/oportunidades/': typeof AppOportunidadesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assinar': typeof AssinarRoute
  '/app/biblioteca': typeof AppBibliotecaRoute
  '/app/calculadoras': typeof AppCalculadorasRoute
  '/app/calendario': typeof AppCalendarioRoute
  '/app/tendencias': typeof AppTendenciasRoute
  '/app': typeof AppIndexRoute
  '/app/oportunidades/$slug': typeof AppOportunidadesSlugRoute
  '/app/oportunidades': typeof AppOportunidadesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/assinar': typeof AssinarRoute
  '/app/biblioteca': typeof AppBibliotecaRoute
  '/app/calculadoras': typeof AppCalculadorasRoute
  '/app/calendario': typeof AppCalendarioRoute
  '/app/tendencias': typeof AppTendenciasRoute
  '/app/': typeof AppIndexRoute
  '/app/oportunidades/$slug': typeof AppOportunidadesSlugRoute
  '/app/oportunidades/': typeof AppOportunidadesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/assinar'
    | '/app/biblioteca'
    | '/app/calculadoras'
    | '/app/calendario'
    | '/app/tendencias'
    | '/app/'
    | '/app/oportunidades/$slug'
    | '/app/oportunidades/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assinar'
    | '/app/biblioteca'
    | '/app/calculadoras'
    | '/app/calendario'
    | '/app/tendencias'
    | '/app'
    | '/app/oportunidades/$slug'
    | '/app/oportunidades'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/assinar'
    | '/app/biblioteca'
    | '/app/calculadoras'
    | '/app/calendario'
    | '/app/tendencias'
    | '/app/'
    | '/app/oportunidades/$slug'
    | '/app/oportunidades/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AssinarRoute: typeof AssinarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assinar': {
      id: '/assinar'
      path: '/assinar'
      fullPath: '/assinar'
      preLoaderRoute: typeof AssinarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/biblioteca': {
      id: '/app/biblioteca'
      path: '/biblioteca'
      fullPath: '/app/biblioteca'
      preLoaderRoute: typeof AppBibliotecaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calculadoras': {
      id: '/app/calculadoras'
      path: '/calculadoras'
      fullPath: '/app/calculadoras'
      preLoaderRoute: typeof AppCalculadorasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendario': {
      id: '/app/calendario'
      path: '/calendario'
      fullPath: '/app/calendario'
      preLoaderRoute: typeof AppCalendarioRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tendencias': {
      id: '/app/tendencias'
      path: '/tendencias'
      fullPath: '/app/tendencias'
      preLoaderRoute: typeof AppTendenciasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/oportunidades/': {
      id: '/app/oportunidades/'
      path: '/oportunidades'
      fullPath: '/app/oportunidades/'
      preLoaderRoute: typeof AppOportunidadesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/oportunidades/$slug': {
      id: '/app/oportunidades/$slug'
      path: '/oportunidades/$slug'
      fullPath: '/app/oportunidades/$slug'
      preLoaderRoute: typeof AppOportunidadesSlugRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBibliotecaRoute: typeof AppBibliotecaRoute
  AppCalculadorasRoute: typeof AppCalculadorasRoute
  AppCalendarioRoute: typeof AppCalendarioRoute
  AppTendenciasRoute: typeof AppTendenciasRoute
  AppIndexRoute: typeof AppIndexRoute
  AppOportunidadesSlugRoute: typeof AppOportunidadesSlugRoute
  AppOportunidadesIndexRoute: typeof AppOportunidadesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBibliotecaRoute: AppBibliotecaRoute,
  AppCalculadorasRoute: AppCalculadorasRoute,
  AppCalendarioRoute: AppCalendarioRoute,
  AppTendenciasRoute: AppTendenciasRoute,
  AppIndexRoute: AppIndexRoute,
  AppOportunidadesSlugRoute: AppOportunidadesSlugRoute,
  AppOportunidadesIndexRoute: AppOportunidadesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AssinarRoute: AssinarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
