// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://shrddigtlyqdsbzjaeiz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNocmRkaWd0bHlxZHNiemphZWl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODU2NzYzNTIsImV4cCI6MjEwMTI1MjM1Mn0.TyCVmKV4XJ6fneU38jWTrC2JD9Mc8yPSh40_PmeV9Yk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});